version: "3.8"

services:
  app:
    image: hexxondiv/morris:2026-04-13-01
    container_name: morris-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./public/uploads:/app/public/uploads